export type { ToolShape } from './lib/tool-shape/tool-shape.types'
export { toolShape, resultNote } from './lib/tool-shape/tool-shape'
export { verbOf, targetOf } from './lib/tool-verb/tool-verb'
export { toolNameOf, shapeOfLine, tally } from './lib/tool-line/tool-line'
export type { DiffLine } from './lib/diff/diff.types'
export { lineDiff, linesOf } from './lib/diff/diff'
export type { ChangeCount } from './lib/change-count/change-count.types'
export { changeCount, changeBadge } from './lib/change-count/change-count'
export { changeLines } from './lib/change-lines/change-lines'
export { ToolIcon } from './ui/ToolIcon/ToolIcon'
export { WorkTrace } from './ui/WorkTrace/WorkTrace'
export type { Mark } from './ui/WorkTrace/work-trace/work-trace.types'
export { ChangeDiff } from './ui/ChangeDiff/ChangeDiff'
