import type { TourStep } from '@/app/demo/tour/tour.types'

// The walk a first-time visitor is taken on. Every stop waits for them: the
// recorded run is held between stops, so the next thing on screen happens
// because they moved on and not because a timer went off while they read.
// The wording says plainly that this is a recording, since a demo that
// pretends to be live is worse than one that says what it is.
export const DEMO_STEPS: TourStep[] = [
  {
    id: 'ask',
    face: 'bunny',
    target: '[data-talk] textarea',
    title: '일 전체를 맡깁니다',
    body: '다음 단계를 지시하는 대신 원하는 결과를 말합니다. 지금 입력되는 문장이 그 예입니다. 누구에게 맡길지는 오케스트레이터가 정합니다.',
    advance: 'manual',
    placement: 'top',
  },
  {
    id: 'crew',
    face: 'bunny',
    target: '[data-card]',
    waitFor: '[data-crew-board="3"]',
    title: '팀원마다 타일 하나',
    body: '세 명이 동시에 붙었습니다. 타일에 이름과 지금 하는 일, 방금 부른 도구가 올라옵니다. 터미널이라면 이 셋의 출력이 한 줄기로 뒤섞였을 자리입니다.',
    advance: 'manual',
    placement: 'bottom',
  },
  {
    id: 'crew-open',
    face: 'planet',
    target: '[data-card]',
    waitFor: '[data-crew-board="3"]',
    title: '타일을 열면 더 들어갑니다',
    body: '팀원 하나를 누르면 무엇을 맡았는지, 지금까지 무슨 도구를 어떤 인자로 불렀는지, 얼마나 썼는지가 아래에 펼쳐집니다. 눌러보세요.',
    advance: 'click',
    placement: 'bottom',
  },
  {
    id: 'approval',
    face: 'star',
    target: '[data-approval]',
    // Only allowing carries the recording on. Turning it down is a real answer
    // the app really takes, so the step stays where it is and the question
    // comes back rather than the tour walking away from it.
    advanceOn: '[data-approval-allow]',
    title: '실행 전에 멈춰서 묻습니다',
    body: '답은 셋입니다. 허용은 이번 한 번만, 거부는 실행하지 않고 그 사정을 팀원에게 돌려보냅니다. 「이번 세션에서는 다시 묻지 않기」는 같은 명령을 이 세션 동안 넘겨 줍니다. 이 기록은 허용된 쪽만 가지고 있어, 거부하면 같은 질문이 다시 올라옵니다.',
    advance: 'click',
    placement: 'right',
  },
  {
    id: 'output',
    face: 'star',
    target: '[data-tick="c6"]',
    // Enabled is what says the output is in: the row is on screen the moment
    // the command is called, and a stop that asks for a press before there is
    // anything to open gets a press that does nothing.
    waitFor: '[data-tick="c6"]:not([disabled])',
    title: '돌아온 출력은 그 자리에 남습니다',
    body: '허용한 명령이 실제로 돌아왔습니다. 줄을 누르면 그때의 출력이 그대로 펼쳐집니다. 터미널을 따로 열 일이 없습니다. 눌러보세요.',
    advance: 'click',
    placement: 'bottom',
  },
  {
    id: 'usage',
    face: 'bunny',
    target: '[data-usage-bar]',
    title: '얼마를 썼는지는 계속 보입니다',
    body: '남은 사용량과 언제 다시 차는지가 아래에 늘 붙어 있습니다. 모델마다 따로, 남은 시간까지 함께 나옵니다. 답변 끝에는 이번 턴이 쓴 토큰과 걸린 시간이 적힙니다. 읽는 동안에도 팀원들은 계속 일하고 있습니다.',
    advance: 'manual',
    placement: 'top',
  },
  {
    id: 'report',
    face: 'bunny',
    target: 'article',
    waitFor: '[data-system-line]',
    // The teammate panel stands a few seconds past the answer, and the
    // conversation widens the instant it goes. Waiting it out is what lets the
    // card be placed once, where it stays.
    waitGone: '[data-crew-board]',
    title: '보고가 한 답변으로 합쳐집니다',
    body: '세 팀원이 각자 올린 결론을 오케스트레이터가 받아 하나로 정리했습니다. 세 갈래로 나가서 한 답변으로 돌아온 것이 이 화면 하나입니다.',
    advance: 'manual',
    placement: 'top',
  },
  {
    id: 'library-open',
    face: 'star',
    target: '[data-library-row]',
    title: '프로젝트의 라이브러리',
    body: '세션이 일하다 남길 만한 결론을 찾으면 제안으로 올립니다. 저절로 저장되는 것은 없습니다. 눌러서 열어보세요.',
    advance: 'click',
    placement: 'right',
  },
  {
    id: 'proposal',
    face: 'star',
    target: '[data-proposals]',
    waitFor: '[data-proposals] button',
    title: '받아들일지는 사람이 정합니다',
    body: '팀원이 올린 제안입니다. 저절로 저장되는 것은 없습니다. 받아들이면 그때 노트가 됩니다.',
    advance: 'click',
    placement: 'bottom',
  },
  {
    id: 'hire',
    face: 'rock',
    target: '[data-hire]',
    title: '팀원은 직접 만듭니다',
    body: '이름과 언제 부를지, 그리고 지시문. 이 셋이면 팀원 하나가 생깁니다. 눌러보세요.',
    advance: 'click',
    placement: 'right',
  },
  {
    id: 'hire-form',
    face: 'rock',
    target: '[data-member-form]',
    waitFor: '#member-prompt',
    title: '무엇까지 정해 줄 수 있는지',
    body: '얼굴과 모델을 고르고, 쓸 도구를 제한하고, 먼저 읽을 문서를 붙이고, 자기 worktree 에서 일할지도 여기서 정합니다. 오케스트레이터는 「언제 부를지」를 읽고 누구에게 맡길지 정합니다.',
    advance: 'manual',
    placement: 'right',
  },
  {
    id: 'git-open',
    face: 'planet',
    target: '[data-git-button]',
    title: '프로젝트의 git 도 여기에',
    body: '팀원들이 각자 브랜치에서 일하고 돌아온 자리입니다. 눌러서 열어보세요.',
    advance: 'click',
    placement: 'bottom',
  },
  {
    id: 'git-graph',
    face: 'planet',
    target: '[data-git-row]',
    title: '누가 무엇을 합쳤는지 보입니다',
    body: '본선 옆으로 갈라졌다 합쳐지는 가지 하나하나가 팀원이 끝내고 돌아온 일입니다. 커밋 하나를 눌러보세요.',
    advance: 'click',
    placement: 'right',
  },
  {
    id: 'git-files',
    face: 'planet',
    target: '[data-git-file] button',
    waitFor: '[data-git-file] button',
    title: '그 커밋이 건드린 파일',
    body: '커밋 하나가 어디를 만졌는지 오른쪽에 섭니다. 파일 하나를 눌러보세요.',
    advance: 'click',
    placement: 'left',
  },
  {
    id: 'git-diff',
    face: 'planet',
    target: '[data-git-diff]',
    waitFor: '[data-git-diff]',
    title: '더한 줄과 지운 줄',
    body: '앱을 떠나지 않고 그 안까지 봅니다. 팀원이 돌려보낸 일을 합치기 전에 여기서 확인합니다.',
    advance: 'manual',
    placement: 'right',
  },
  {
    id: 'settings-open',
    face: 'bunny',
    target: '[data-settings-button]',
    title: '무엇까지 맡길지 정합니다',
    body: '계정, 프로젝트, 모델, 그리고 묻지 않고 어디까지 해도 되는지. 눌러서 열어보세요.',
    advance: 'click',
    placement: 'bottom',
  },
  {
    id: 'settings-session',
    face: 'bunny',
    target: '[data-setup-section="session"]',
    waitFor: '[data-setup-section="session"]:not([hidden])',
    title: '권한과 모델은 여기서',
    body: '아까처럼 매번 묻게 할지, 아예 묻지 않게 할지가 여기서 정해집니다. 계획부터 · 바꿀 때 묻기 · 자동 편집 · 전부 허용 중에 고르고, 모델과 노력 수준도 함께 정합니다. 다음 세션부터 그대로 적용됩니다.',
    advance: 'manual',
    placement: 'left',
  },
  {
    id: 'outro',
    face: 'bunny',
    target: null,
    title: '여기까지입니다',
    body: '실제 앱은 여러분 컴퓨터의 Claude Code 를 그대로 실행합니다. 대화도 팀원도 라이브러리도 전부 로컬에 남고, 로그인은 CLI 가 관리합니다. 내려받기와 자세한 소개는 Zetrem 홈페이지에 있습니다.',
    advance: 'manual',
  },
]
