export { canSignIn, needingAuth, readConnectors } from './lib/read-connectors/read-connectors'
export type { Connector, ConnectorState, ConnectorVerb } from './lib/read-connectors/read-connectors.types'
export { refusalOf, tidyName } from './lib/new-connector/new-connector'
export type { NewConnector, Refusal, RefusalCode } from './lib/new-connector/new-connector.types'
export { refusalWhy, saidOrWhy } from './lib/refusal-why/refusal-why'
export { brandOf } from './lib/brand/brand'

export { originOf, removableConnector, shortName } from './lib/origin/origin'
export { connectorGroupsOf } from './lib/groups/groups'
export type { ConnectorGroup } from './lib/groups/groups.types'
export type { ConnectorOrigin } from './lib/origin/origin.types'
